export const BUSINESSES = [
  {
    id: 'b1',
    name: 'سالن زیبایی نازنین',
    address: 'کرمان، بلوار حمزه، کوچه ۱۰',
    instagram: '@nazanin_beauty',
    description: 'ارائه دهنده تخصصی خدمات تراپی و کراتین مو با بهترین مواد روز دنیا در محیطی آرام و دلپذیر.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/114603/m06a16wns0I_QQ-QOTddZA.png',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/114603/m06a16wns0I_QQ-QOTddZA.png',
    rating: 4.8,
    hasSnappPay: true,
    workingHours: 'همه روزه ساعت ۱۰ صبح تا ۸ شب',
  },
  {
    id: 'b2',
    name: 'مرکز پوست و زیبایی ماه',
    address: 'کرمان، خیابان شریعتی، مجتمع الماس',
    instagram: '@mah_skin_care',
    description: 'تخصصی ترین مرکز فیشیال و پاکسازی پوست در کرمان با استفاده از پیشرفته ترین دستگاه ها.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/112711/rlAHNTWZQVAsCJf83C5cPw.jpeg',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/112711/rlAHNTWZQVAsCJf83C5cPw.jpeg',
    rating: 4.5,
    hasSnappPay: false,
    workingHours: 'شنبه تا پنجشنبه ساعت ۹ صبح تا ۷ عصر',
  },
  {
    id: 'b3',
    name: 'سالن زیبایی آوینا',
    address: 'کرمان، هزار و یک شب، بین کوچه ۵ و ۷',
    instagram: '@avina_nail',
    description: 'خدمات حرفه ای ناخن، مانیکور و پدیکور با جدیدترین متدها و تنوع رنگی بی نظیر.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/101015/0ZuchDERMPxI4pMcFTOAcQ.PNG',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/101015/0ZuchDERMPxI4pMcFTOAcQ.PNG',
    rating: 4.7,
    hasSnappPay: true,
    workingHours: 'شنبه تا چهارشنبه ساعت ۱۱ صبح تا ۹ شب',
  },
  {
    id: 'b4',
    name: 'کلینیک زیبایی یاس',
    address: 'کرمان، شهرک مطهری، نبش کوچه ۱۲',
    instagram: '@yas_clinic',
    description: 'کلینیک تخصصی پوست و مو، فیشیال تخصصی و جوانسازی تحت نظر پزشک متخصص.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/63317/ZBr69rE1oRKzOnGOvOpnsw.JPG',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/63317/ZBr69rE1oRKzOnGOvOpnsw.JPG',
    rating: 4.9,
    hasSnappPay: true,
    workingHours: 'همه روزه ساعت ۸ صبح تا ۶ عصر',
  },
  {
    id: 'b5',
    name: 'سالن زیبایی نیلا',
    address: 'کرمان، بلوار جمهوری، کوچه ۱۸',
    instagram: '@nila_haircolor',
    description: 'تخصص در رنگ و لایت، آمبره و سامبره با تکنیک های روز و مواد بدون آسیب.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/119592/12jb-WdhETVbGlNIe5LvKw.png',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/119592/12jb-WdhETVbGlNIe5LvKw.png',
    rating: 4.6,
    hasSnappPay: false,
    workingHours: 'شنبه تا پنجشنبه ساعت ۱۰ صبح تا ۸ شب',
  },
  {
    id: 'b6',
    name: 'مرکز مراقبت پوست آیلین',
    address: 'کرمان، شهرک باهنر ، ساختمان پزشکان آفتاب',
    instagram: '@aylin_skincare',
    description: 'ارائه دهنده خدمات مزوتراپی، میکرونیدلینگ و جوانسازی پوست به صورت کاملا تخصصی.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/100410/xvM7_dHdgzyAGCYKcqmRTQ.jpg',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/113533/a0jQueHo7JDieIhR5cCdHw.jpg',
    rating: 4.4,
    hasSnappPay: true,
    workingHours: 'شنبه تا چهارشنبه ساعت ۹ صبح تا ۵ عصر',
  },
];

export const DEALS = [
  {
    id: 'd1',
    businessId: 'b1',
    businessName: 'سالن زیبایی نازنین',
    serviceTitle: 'کراتین و احیای مو',
    originalPrice: 624000,
    discountedPrice: 384000,
    discountPercentage: 52,
    purchasesCount: 38,
    expiryDate: '۱۴۰۵/۰۳/۱۵',
    imageUrl: 'https://www.digikala.com/mag/wp-content/uploads/2023/04/keratine.jpg',
    category: 'hair',
  },
  {
    id: 'd1_2',
    businessId: 'b1',
    businessName: 'سالن زیبایی نازنین',
    serviceTitle: 'براشینگ تخصصی',
    originalPrice: 717000,
    discountedPrice: 430000,
    discountPercentage: 22,
    purchasesCount: 24,
    expiryDate: '۱۴۰۵/۰۳/۱۵',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlcww6J-xMRPPp77rtQYA92fKJiuyiQqH0wCu08ghmeA&s',
    category: 'hair',
  },
  {
    id: 'd2',
    businessId: 'b2',
    businessName: 'مرکز پوست و زیبایی ماه',
    serviceTitle: 'پاکسازی و فیشیال کلاسیک',
    originalPrice: 1200000,
    discountedPrice: 595000,
    discountPercentage: 46,
    purchasesCount: 42,
    expiryDate: '۱۴۰۵/۰۳/۲۰',
    imageUrl: 'https://i1.delgarm.com/i/828/020813/65462621f1fcd.jpeg',
    category: 'skin',
  },
  {
    id: 'd2_2',
    businessId: 'b2',
    businessName: 'مرکز پوست و زیبایی ماه',
    serviceTitle: 'ماساژ صورت هیدرودرمی',
    originalPrice: 500000,
    discountedPrice: 300000,
    discountPercentage: 40,
    purchasesCount: 19,
    expiryDate: '۱۴۰۵/۰۳/۲۰',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/114348/cnOIHeAIc43Edf8365_CWg.jpg',
    category: 'skin',
  },
  {
    id: 'd3',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'مانیکور و پدیکور VIP',
    originalPrice: 450000,
    discountedPrice: 315000,
    discountPercentage: 20,
    purchasesCount: 31,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://s100.divarcdn.com/static/photo/neda/webp_post/XKFm7wuH5n49OEtSINyuBg/1d1f88a6-657e-4686-a30c-c08515762e56.webp',
    category: 'nail',
  },
  {
    id: 'd3_2',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'ژلیش ناخن دست',
    originalPrice: 200000,
    discountedPrice: 189000,
    discountPercentage: 6,
    purchasesCount: 27,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwyLFBKNs_rU__HQ2WaM28DIbA_HWIBl0vxBSeXF2WvUUn-qV5pc7tyXb1&s=10',
    category: 'nail',
  },
  {
    id: 'd3_3',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'کاشت ناخن پودری',
    originalPrice: 600000,
    discountedPrice: 420000,
    discountPercentage: 34,
    purchasesCount: 45,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmgtWbU5MVIxtkEJ5nLDyo2lsh6aLtgVDLjDqn6NN80OUmAJrV1cWuVCVE&s=10',
    category: 'nail',
  },
  {
    id: 'd3_4',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'پارافین تراپی دست',
    originalPrice: 570000,
    discountedPrice: 332000,
    discountPercentage: 9,
    purchasesCount: 18,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://www.digikala.com/mag/wp-content/uploads/2024/04/paraffin-Treatment-3.jpg',
    category: 'nail',
  },
  {
    id: 'd4',
    businessId: 'b4',
    businessName: 'کلینیک زیبایی یاس',
    serviceTitle: 'فیشیال تخصصی جوانسازی',
    originalPrice: 1800000,
    discountedPrice: 1390000,
    discountPercentage: 6,
    purchasesCount: 36,
    expiryDate: '۱۴۰۵/۰۳/۱۰',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1UJRsBWsbkPMBF4gELSsNquRQI4z0LJxkZ8fxYzbDDT2BxaZ4ZjGYi_Fj&s=10',
    category: 'medical',
  },
  {
    id: 'd4_2',
    businessId: 'b4',
    businessName: 'کلینیک زیبایی یاس',
    serviceTitle: 'تزریق بوتاکس مصپورت',
    originalPrice: 2800000,
    discountedPrice: 1350000,
    discountPercentage: 35,
    purchasesCount: 41,
    expiryDate: '۱۴۰۵/۰۳/۱۰',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYaeCmuX8patY9oot0U7HU606Z-TZXIbUYRsWr76XjOobO4ljLkW4Qmm8&s=10',
    category: 'medical',
  },
  {
    id: 'd5',
    businessId: 'b5',
    businessName: 'سالن زیبایی نیلا',
    serviceTitle: 'رنگ و لایت تخصصی',
    originalPrice: 3500000,
    discountedPrice: 2450000,
    discountPercentage: 30,
    purchasesCount: 29,
    expiryDate: '۱۴۰۵/۰۴/۰۱',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrDacnFl0RJ_EOwFFMIFl_WWhDpAkd2Fssb2GJqM1nKtIOkxgrNNHvhYSt&s=10',
    category: 'hair',
  },
  {
    id: 'd6',
    businessId: 'b6',
    businessName: 'مرکز مراقبت پوست آیلین',
    serviceTitle: 'مزوتراپی مو سر',
    originalPrice: 1800000,
    discountedPrice: 1260000,
    discountPercentage: 30,
    purchasesCount: 33,
    expiryDate: '۱۴۰۵/۰۳/۳۰',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=96191/production/package/images/264996/nxsts6x3_HGcrdKViRJJrQ.png',
    category: 'medical',
  },
];